### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by thijstriemstra** [jhildenbiddle/canvas-size#1]
This library does not clean out the memory it's using. Before Chrome uses 116mb, after calling 

```javascript
canvasSize.maxArea({
        onError: (width, height) => {
            console.warn('canvas.maxArea Error:', width, height);
        },
        onSuccess: (width, height) => {
            console.log('canvas.maxArea - width: ' + width.toLocaleString() +
                'px, height: ' + height.toLocaleString() + 'px');
        }
    });
```

Chrome now uses 1.1GB and does not release that additional 1GB (!).

**Comment by jhildenbiddle** [comment]
Fixed in 1.0.4.

Thanks for filing the issue!

**Comment by thijstriemstra** [comment]
Not sure, but still see a 1GB load when calling this method.

**Comment by jhildenbiddle** [comment]
Memory usage will spike for the test, then drop back down once garbage collection kicks in. 

There's no way around the memory spike while testing because creating large canvas elements take up a lot of memory. Firefox seems to fair a bit better than Edge and Webkit-based browsers in terms of memory usage (~500mb for Firefox vs. ~1gb for Chrome/Edge/Safari), but all of these browsers return to normal, pre-canvasSize memory usage after about 1-5 seconds in my tests.

Steps to replicate tests:

1. Launch Activity Monitor (Mac) or Task Manager (Windows)
1. Launch a browser
1. Navigate to https://htmledit.squarefree.com and note memory usage
1. Paste the following code to test the old version (1.0.3) and note memory usage (spike and sustained)

   ```html
   <pre></pre>
   <script src="https://cdn.jsdelivr.net/npm/canvas-size@1.0.3/dist/canvas-size.min.js"></script>
   <script>
       canvasSize.maxArea({
           onError: (width, height) => {
               document.querySelector('pre').textContent += `Error  : ${width} x ${height}\n`;
           },
           onSuccess: (width, height) => {
               document.querySelector('pre').textContent += `Success: ${width} x ${height}\n`;
           }
       });
   </script>
   ```

1. Close the tab
1. Open a new tab
1. Navigate to https://htmledit.squarefree.com and note memory usage
1. Paste the following code to test the new version (1.0.4) and note memory usage (spike and sustained)

   ```html
   <pre></pre>
   <script src="https://cdn.jsdelivr.net/npm/canvas-size@1.0.4/dist/canvas-size.min.js"></script>
   <script>
       canvasSize.maxArea({
           onError: (width, height) => {
               document.querySelector('pre').textContent += `Error  : ${width} x ${height}\n`;
           },
           onSuccess: (width, height) => {
               document.querySelector('pre').textContent += `Success: ${width} x ${height}\n`;
           }
       });
   </script>
   ```

Hope this helps.

**Comment by thijstriemstra** [comment]
```
Close the tab

Open a new tab
```

Sure this will fix it but this is not optimal. I will look into caching the value. Thanks for the detailed feedback.

**Comment by jhildenbiddle** [comment]
I think you're missing the point of those steps. 

The steps above are provided so you can see how the old and new versions behave differently. They are not steps for how to "fix" memory consumption issues. Each version has to be tested in separate tabs.

If you prefer, try this:

1. Launch Activity Monitor (Mac) or Task Manager (Windows)
1. Launch a browser
1. Launch two tabs
1. In both tabs, navigate to https://htmledit.squarefree.com and note memory usage
1. In the first tab, paste the following code to test the old version (1.0.3) and note memory usage (spike and sustained)

   ```html
   <pre></pre>
   <script src="https://cdn.jsdelivr.net/npm/canvas-size@1.0.3/dist/canvas-size.min.js"></script>
   <script>
       canvasSize.maxArea({
           onError: (width, height) => {
               document.querySelector('pre').textContent += `Error  : ${width} x ${height}\n`;
           },
           onSuccess: (width, height) => {
               document.querySelector('pre').textContent += `Success: ${width} x ${height}\n`;
           }
       });
   </script>
   ```

1. In the second tab, paste the following code to test the new version (1.0.4) and note memory usage (spike and sustained)

   ```html
   <pre></pre>
   <script src="https://cdn.jsdelivr.net/npm/canvas-size@1.0.4/dist/canvas-size.min.js"></script>
   <script>
       canvasSize.maxArea({
           onError: (width, height) => {
               document.querySelector('pre').textContent += `Error  : ${width} x ${height}\n`;
           },
           onSuccess: (width, height) => {
               document.querySelector('pre').textContent += `Success: ${width} x ${height}\n`;
           }
       });
   </script>
   ```

**Comment by thijstriemstra** [comment]
I'm one of the maintainers of https://github.com/katspaugh/wavesurfer.js and would like to incorporate a light-weight library to get the max canvas size, but I'm not sure if this library would be up for that task?

**Comment by jhildenbiddle** [comment]
What concerns do you have or issues are you running into?

Your initial statement about the memory leak was accurate. The [fix](https://github.com/jhildenbiddle/canvas-size/commit/0f24f5266889260deb4e2a92a98491784d942ab0#diff-1fdf421c05c1140f6d71444ea2b27638) was a simple and has been implemented in the latest release (1.0.4). Based on my tests in Chrome, Edge, Firefox, and Safari, the memory leak is no longer an issue.

There is--and will continue to be--a temporary memory spike that occurs when testing large canvas sizes. This is unavoidable, as creating large canvas elements requires large amounts of memory. The size of the spike will be proportional to size of the canvas being tested (the bigger the canvas, the more memory consumed). The important thing to realize is that memory consumption will return to normal once maximum area/height/width are determined and the browser's automated garbage collection kicks in.

Here are a series of screenshots demonstrating the above scenario:

1. Initial page load. Memory used is 18K

![1](https://user-images.githubusercontent.com/442527/55907442-a480d880-5b8b-11e9-92c6-7c3e46dd6acd.png)

2. canvasSize library determining max area using default values. Memory used is 527K.

![2](https://user-images.githubusercontent.com/442527/55907536-e6aa1a00-5b8b-11e9-9a3d-e767f15eff71.png)

3. canvasSize library completed max area test. Memory remains at 527K because the Chrome's garbage collection has yet to kick in.

![3](https://user-images.githubusercontent.com/442527/55907628-1f49f380-5b8c-11e9-9833-c6fc2a06eb1b.png)

4. Chrome's automated garbage collection has completed. Memory used is now at 20K.

![4](https://user-images.githubusercontent.com/442527/55907706-54564600-5b8c-11e9-9112-d5fdb97a1f2f.png)

A few items regarding usage in your application:

1. To reduce memory consumption and test times, test the max values you need instead of the max values possible. For example, don't call `maxArea` using the default values (16384 x 16384) if your application only renders a canvas as large as the user's screen (e.g 1280x800, 1920x1080, etc.)

1. As mentioned in the [Known Issues](https://github.com/jhildenbiddle/canvas-size#known-issues) section of the docs, the single-threaded nature of web browsers means your application's UI can become unresponsive during `canvasSize` tests (click the link for details). The best way to work around this is to avoid calling `canvasSize` *every* time you need to render a canvas, and instead testing for the maximum canvas area/height/width your application will use and [storing these results](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage).

1. A future version of the library could use the new [Offscreen Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) to work around the single-threaded / unresponsive UI issue above. This enhancement wouldn't affect test times or memory consumption, but it would offload testing to another thread which would prevent the browser from becoming temporarily unresponsive during tests. If this is something you would like to see added, I can try to carve out some time to work on it.

Hope this helps. Let me know if you have any other questions or concerns.

**Comment by thijstriemstra** [comment]
I really appreciate the amount of effort you put in your replies, and it makes me more confident about the long-term viability of this library.

Perhaps you should also have a hard-coded version of the browser results that can be queried. I'm not so much interested in the latest and greatest results from a realtime test, it's not that browser vendors will ever *decrease* the canvas size.

Thoughts?

**Comment by thijstriemstra** [comment]
> A future version of the library could use the new Offscreen Canvas API to work around the single-threaded / unresponsive UI issue above. This enhancement wouldn't affect test times or memory consumption,

Unfortunately, from my tests, `OffscreenCanvas` is susceptible to memory issues and like you said, memory consumption will be the same.

**Comment by thijstriemstra** [comment]
And ps. your suggestion to cache these values: I think that should be (able to) handled by this library.

**Comment by jhildenbiddle** [comment]
> Perhaps you should also have a hard-coded version of the browser results that can be queried. I'm not so much interested in the latest and greatest results from a realtime test, it's not that browser vendors will ever decrease the canvas size.

The library already contains [hard-coded values](https://github.com/jhildenbiddle/canvas-size/blob/00c259f42c6d33a043ebf17d1c9ccf15520adb15/src/index.js#L12-L71) based on [previous test results](https://github.com/jhildenbiddle/canvas-size#test-results), but they are not used in the way you are describing.

Browsers behave differently based on their environment and the resources available to them (see [Known Issues #2](https://github.com/jhildenbiddle/canvas-size#known-issues)). For example, a browser running on hardware without GPU acceleration or with limited memory can return different results for this library. It is therefore not safe to assume the max canvas area/height/width values based on the browser being used.

Take a look at the [last screenshot](https://user-images.githubusercontent.com/442527/55907706-54564600-5b8c-11e9-9112-d5fdb97a1f2f.png) above. It shoes Chrome 73 on Ubuntu Linux 18.04 failing to render a canvas at 16384 x 16384, yet the same test using Chrome 70 on Win/Mac passed this test without issue. Why? Because I am running Ubuntu using a virtual machine. How will Chrome run on a [Rasberry Pi](https://www.raspberrypi.org/) or a VM in the Amazon/Google/Microsoft cloud? I have no idea, but this is the exact question this library aims to answer.

> And ps. your suggestion to cache these values: I think that should be (able to) handled by this library.

It's possible, but it seems unnecessary given how trivial it is to do on your own.

```js
// Standard variables
let maxAreaHeight, maxAreaWidth;

canvasSize.maxArea({
  onSuccess(width, height) {
    maxAreaHeight = height;
    maxAreaWidth = width;
  }
});
```

```js
// Local storage
canvasSize.maxArea({
  onSuccess(width, height) {
    localStorage.setItem('maxAreaHeight', height);
    localStorage.setItem('maxAreaWidth', width);
  }
});

// Get values
localStorage.getItem('maxAreaHeight');
localStorage.getItem('maxAreaWidth');
```

None of this is hard to bake into the library, but different scenarios call for different methods of storing values (or perhaps the values don't need to be stored at all). The library will provide you with the max area/height/width values, but how you use them is up to you.

**Comment by thijstriemstra** [comment]
Well, again thanks for the details, but I'm not wiling to take a performance hit for a nr like 16384. 

> The library already contains hard-coded values based on previous test results, but they are not used in the way you are describing.

Then I'll take a look at that, cheers. I need 99% guarantee and what it returns on an RPI chromium is 99% to be the same as on 64-bit ubuntu chrome.

**Comment by jhildenbiddle** [comment]
Respectfully, it sounds like you are confusing theoretical browser limitations (i.e. "What is the largest canvas Chrome can render") with *real-world* limitations that will affect your app (i.e. "What is the largest canvas Chrome can render *on this system*?"). These values are not guaranteed to be the same. That's why this library exists.

You're also assuming all users will be using Chrome, but official browser support wavesurfer.js states otherwise:

> wavesurfer.js works only in [modern browsers supporting Web Audio](https://caniuse.com/#feat=audio-api).

Are you intending to also detect and hard code canvas values for Edge, IE, Firefox, and Safari? What about detecting Safari on iOS vs. Mac? Chrome on Mac/Win/Linux vs. Android vs. ChromeOS? What about [Microsoft's new Chromium-based version of Edge](https://www.cnet.com/news/microsoft-releases-its-google-chrome-like-edge-browser-for-testing/)?

Finally, regarding performance, I've created a demo with benchmarks to help put things in perspective:

* https://jsbin.com/bilahapufo/edit?js,output

On a 2009 Mac Pro testing with Chrome 73 I get the following:

* Maximum area  : 16384 x 16384 (0.69s)
* Maximum area  : 5120 x 5120 (0.04s)
* Maximum height: 1 x 32767 (0.02s)
* Maximum width : 32767 x 1 (0.02s)

I don't know what your performance targets are, but it's hard to imagine a test for 5K (5120px) support on 10-year-old hardware taking 0.04s will be perceived as a performance issue for a waveform visualization library. Just my $0.02.

Whichever way you go, good luck with your project. It looks pretty slick.

**Comment by thijstriemstra** [comment]
To keep the conversation going, and to respond to your points about wavesurfer: the way it's implemented now, is that a high zoom level will create x amount of huge canvasses (with a width of 16384 for example, value from your lib for example) and render those. It's something I'd like to fix, and the size of a canvas is one of the first things I noticed could be a potential problem. I'd like to know how big a canvas can be in the client's browser.

**Comment by jhildenbiddle** [comment]
Got it.

This library can answer the "how big a canvas can be in the client's browser" question, but I think you're going to run into issues rendering multiple large canvas elements (especially on memory-constrained and/or lower-end hardware with limited GPU acceleration).

I took a look at the [zoom example](https://wavesurfer-js.org/example/zoom/index.html) so I have a better idea of what you're referring to now.

It looks like you're offloading the "resize the waveform visualization" work to the browser by rending a 1:1 canvas and then reducing the width to simulate "zoom out". That works, but it has two major drawbacks: 1) it has the potential to consume lots of memory, and 2) it requires rendering the waveform visualization using multiple canvas elements when the visualization is larger than largest canvas element a browser can render.

A more efficient approach would be to render a single canvas element and resize the waveform visualization before rendering it to the canvas. This should perform much better than rendering multiple canvas elements since you will only need to render the part of the waveform that is visible to the user. It also means you won't have to manage rendering large waveform visualizations using multiple canvas elements.

There are other approaches too, like generating the waveform in `<svg>` markup, rendering that to a canvas, and either specifying the offset (to simulate moving left/right) or resizing the svg for zoom in/out. I don't know how performant this would be though, so it would require some experimentation.
